### ISSUE TITLE
custom /proc

### ISSUE THREAD

**Issue by wenzowski** [lorieri/coreos-newrelic#1]
does starting with nspawn help with the /proc problem?
https://discuss.newrelic.com/t/newrelic-monitoring-with-coreos/1502/15

**Comment by wenzowski** [comment]
I see the `--bind=/proc:/proc` and am hoping so...

**Comment by lorieri** [comment]
I think the bind is not even needed, but since it worked I did not test without it
https://github.com/coreos/toolbox/blob/23fffeffef680ed4cab13d214abd609acbb4024a/toolbox

**Comment by wenzowski** [comment]
cool! thanks for this

**Comment by lorieri** [comment]
:smile:

**Comment by lorieri** [comment]
Hi, just updated it
removed systemd-nspawn
